### PR TITLE
add variable.md

### PR DESCRIPTION
**Pull request by Naris167**

### CODE REVIEW

**Comment by chinathaip** [comment]
Coolio

**Comment by chinathaip** [comment]
Btw it collapses a bit with "data type" chapter. Wdyt @Lxkas

**Comment by Lxkas** [comment]
> Btw it collapses a bit with "data type" chapter. Wdyt @Lxkas

yeah in call with naris rn, figuring it out XD

**Comment by chinathaip** [comment]
@Lxkas  can we merge this? will deploy to dev soon

**Comment by Lxkas** [comment]
Sure, can merge

**Review by chinathaip — APPROVED** [review]

**Comment by chinathaip** [comment]
Okie

**Review by Lxkas — APPROVED** [review]

**Pull request merged**
